# Generated by Django 5.0.2 on 2024-04-25 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='capas_livros')),
                ('estado', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('P', 'Para Doação'), ('D', 'Doação Realizada')], max_length=1)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='divulgar.genero')),
                ('tags', models.ManyToManyField(to='divulgar.tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
