# Generated by Django 5.0.2 on 2024-04-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0004_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
